# Generated by Django 4.2 on 2023-04-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('fecha_inicio_proyecto', models.DateField()),
                ('fecha_fin_proyecto', models.DateField()),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_rol', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id_proyecto_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.roles')),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectos')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuarios')),
            ],
            options={
                'verbose_name': 'usuario_proyecto',
                'verbose_name_plural': 'usuario_proyectos',
                'db_table': 'usuario_proyecto',
            },
        ),
    ]
