# Generated by Django 4.2 on 2023-04-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_fin_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_inicio_proyecto',
        ),
    ]
