# Generated by Django 4.2 on 2023-04-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyectos_fecha_fin_proyecto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectoUsuario',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
