# Generated by Django 4.2 on 2023-04-26 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id_sprint', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sprint', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin_prev', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'db_table': 'sprints',
            },
        ),
    ]
