# Generated by Django 4.2 on 2023-05-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_delete_proyectousuario_delete_roles'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprints',
            name='id_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprints',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='fecha_fin_prev',
            field=models.DateField(default='2023-06-06'),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='fecha_inicio',
            field=models.DateField(default='2023-05-23'),
        ),
    ]
