# Generated by Django 4.2 on 2023-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_sprints_id_proyecto_alter_sprints_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprints',
            name='fecha_fin_prev',
            field=models.DateField(default='2023-07-07'),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='fecha_inicio',
            field=models.DateField(default='2023-06-23'),
        ),
    ]
