# Generated by Django 4.2 on 2023-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosUserStory',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'estadouserstory',
                'verbose_name_plural': 'estadosuserstories',
                'db_table': 'estados_userstory',
            },
        ),
    ]
