# Generated by Django 4.2 on 2023-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('usuario_sistema', models.CharField(max_length=50)),
                ('contrasenha', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddIndex(
            model_name='usuarios',
            index=models.Index(fields=['id_usuario', 'nombre_usuario'], name='idx_usuarios_id_nombre'),
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('usuario_sistema',), name='unique_usuario_sistema'),
        ),
    ]
