# Generated by Django 4.2 on 2023-04-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('rol', '0001_initial'),
        ('proyecto', '0003_delete_proyectousuario_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id_proyecto_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.roles')),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectos')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuarios')),
            ],
            options={
                'verbose_name': 'proyectousuario',
                'verbose_name_plural': 'proyectousuarios',
                'db_table': 'usuario_proyecto',
            },
        ),
    ]
