# Generated by Django 4.2 on 2023-04-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectousuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectousuario',
            old_name='nombre_proyecto',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='proyectousuario',
            old_name='descripcion_rol',
            new_name='id_rol',
        ),
        migrations.RenameField(
            model_name='proyectousuario',
            old_name='nombre_usuario',
            new_name='id_usuario',
        ),
    ]
